#!/bin/sh
PORT=2002

# Default flags to pass to the MUD server (see admin.txt for a description
# of all flags).
FLAGS='-q'

#############################################################################

while ( : ) do

  DATE=`date`
  echo "autorun starting game $DATE" >> syslog
  echo "running bin/aarait $FLAGS $PORT" >> syslog

  bin/aarait $FLAGS $PORT >> syslog 2>&1

  tail -30 syslog > syslog.CRASH

  fgrep "self-delete" syslog >> log/delete
  fgrep "killed" syslog >> log/rip
  fgrep "has been slain by" syslog >> log/rip
  fgrep "Running" syslog >> log/restarts
  fgrep "advanced" syslog >> log/levels
  fgrep "equipment lost" syslog >> log/rentgone
  fgrep "usage" syslog >> log/usage
  fgrep "new player" syslog >> log/newplayers
  fgrep "SYSERR" syslog >> log/errors
  fgrep "(GC)" syslog >> log/godcmds
  fgrep "Bad PW" syslog >> log/badpws
  fgrep "OLC" syslog >> log/olc
  fgrep "JOB:" syslog >> log/quest
  fgrep "(JOB)" syslog >> log/quest
  fgrep "THIEF" syslog >> log/thief
  fgrep "HOUSE" syslog >> log/clan
  fgrep "CHEAT" syslog >> log/cheaters
  fgrep "MISSING HELP" syslog >> log/helps

  rm log/syslog.1
  mv log/syslog.2 log/syslog.1
  mv log/syslog.3 log/syslog.2
  mv log/syslog.4 log/syslog.3
  mv log/syslog.5 log/syslog.4
  mv log/syslog.6 log/syslog.5
  mv syslog       log/syslog.6
  touch syslog

#  if [ -r lib/core ]; then
#    rm lib/core
#  fi

  if [ ! -r .fastboot ]; then
    sleep 10 
  else
    rm .fastboot
    sleep 5
  fi

  if [ -r .killscript ]; then
    DATE=`date`;
    echo "autoscript killed $DATE"  >> syslog
    rm .killscript
    exit
  fi

  gdb bin/aarait lib/core < q >> log/core.log


  while [ -r pause ]; do
    sleep 60
  done

  if [ -r update ]; then
    cp ~/dibrova~/bin/circle ~/prod/bin/
    rm update
  fi

done
