extern const char *circlemud_version;
extern const char *dirs[];
extern const char *room_bits[];
extern const char *exit_bits[];
extern const char *sector_types[];
extern const char *genders[];
extern const char *position_types[];
extern const char *player_bits[];
extern const char *action_bits[];
extern const char *preference_bits[];
extern const char *affected_bits[];
extern const char *connected_types[];
extern const char *where[];
extern const char *equipment_types[];
extern const char *item_types[];
extern const char *wear_bits[];
extern const char *extra_bits[];
extern const char *apply_types[];
extern const char *container_bits[];
extern const char *drinks[];
extern const char *drinknames[];
extern const char *color_liquid[];
extern const char *fullness[];
extern const char *spell_wear_off_msg[];
extern const char *npc_class_types[];
extern const char *weekdays[];
extern const char *month_name[];
extern const struct str_app_type str_app[];
extern const struct dex_skill_type dex_app_skill[];
extern const struct dex_app_type dex_app[];
extern const struct con_app_type con_app[];
extern const struct int_app_type int_app[];
extern const struct wis_app_type wis_app[];
extern int drink_aff[][3];
extern const char *spell_wear_off_msg[];
extern const int rev_dir[];
extern const int movement_loss[];
extern const char *weekdays[];
extern const char *month_name[];
extern const char *pc_class_types[];
extern const char *noble_houses[];
extern const char *no_house_noble_houses[];
extern const char *npc_class_types[];
extern const char *npc_race_types[];
extern const char *pc_race_types[];
extern const char *rank[][3];
extern const char *stat_names[];
extern const int house_load_rooms[];
extern const char *skill_names[];
extern const int job_needs[][2];
extern const char *AssemblyTypes[];
extern const char *jtypes[];
extern const int ability_modifer[];
extern const char *mob_sizes[];
extern const char *coin_types[];
extern const char *fish_tips[];
extern const char *pig_tips[];
extern const char *livestock_afraid_vocals[];
extern const char *items_to_eat[];

